baseURL: "https://korfball4all.co.uk" 
title: Korfball For All
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Letter
          url: letter/
          weight: 5
        - name: Co-sign the letter
          url: https://docs.google.com/forms/d/e/1FAIpQLSexgN4uZ_ohFDFGAYzjveEcj0GJ19RXTdDan8sM83Lb6jkl_w/viewform?usp=header
          weight: 6
        - name: Campaign Progress
          url: progress/
          weight: 7
        - name: EK Gender Policy
          url: https://englandkorfball.co.uk/england-korfball-gender-policy/
          weigth: 8


params:
    description: "This is a website built to urge England Korfball (and the IKF) to adopt more inclusive policies for Korfball. So Korfball is again for everyone."
    author: Jennifer Cresswell
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "November 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["letter","sign"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Korfball For All
          subtitle: "Hi, I'm Jenny, I am a trans woman who has played Korfball since 2019. I believe everyone should feel welcome to play Korfball."
          subtitle2: "The latest England Korfball gender policy actively works against inclusion, so I made this site to call for change, and get the backing of the Korfball community!"
          subtitle3: "For information on why the new policy is discriminatory and uninclusive, please see the letter I have written, and co-sign if you agree the policy should change!"
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Letter
              url: letter/
            - name: Co-sign the letter
              url: https://docs.google.com/forms/d/e/1FAIpQLSexgN4uZ_ohFDFGAYzjveEcj0GJ19RXTdDan8sM83Lb6jkl_w/viewform?usp=header
            - name: Campaign progress
              url: progress/
            - name: EK Gender Policy
              url: https://englandkorfball.co.uk/england-korfball-gender-policy/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Korfball for All"
      icon: picture.png
      iconHeight: 18
    sigbanner:
      signatures: 118
      clubs: 27
      message: "Signatures: "
      message2: "Clubs represented: "

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2